<?php
/**
 * Created by PhpStorm.
 * User: MACHENIKE
 * Date: 2018/6/17
 * Time: 15:49
 */

namespace Swoole\Controller;

use Org\Swoole\BaseSwoole;
use Org\Swoole\Swoole;

class WebSocketController extends Swoole {

    use BaseSwoole;

    protected $_serv = null;
    protected $host = '0.0.0.0';

    public function __construct() {

        //swoole所在目录
        $this->swoole_path = __DIR__;
        $this->swoole_task_name_pre = 'webSocket';
        $this->swoole_task_pid_path = DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'webSocket-task.pid';
        parent::__construct();
        return $this->base();
    }

    /**
     * 核心运行
     */
    public function run()
    {
        // TODO: Implement run() method.
        $this->_serv = new \swoole_websocket_server($this->_setting['host'], $this->_setting['port']);

        $this->_serv->set([
//            'worker_num'        => $this->_setting['worker_num'],
//            'task_worker_num'   => $this->_setting['task_worker_num'],
//            'task_ipc_mode '    => $this->_setting['task_ipc_mode'],
//            'task_max_request'  => $this->_setting['task_max_request'],
            'daemonize'         => $this->_setting['daemonize'],
            'max_request'       => $this->_setting['max_request'],
            'dispatch_mode'     => $this->_setting['dispatch_mode'],
            'log_file'          => $this->_setting['log_file']
        ]);
        $this->_serv->on('Start', array($this, 'onStart'));
        $this->_serv->on('open', [$this,'onOpen']);
        $this->_serv->on('message',[$this,'onMessage']);
        $this->_serv->on('request',[$this,'onRequest']);
        $this->_serv->on('close',[$this,'onClose']);

        $this->_serv->start();
    }

    /**
     * 客户端连接服务端
     * @param \Org\Swoole\服务端数据 $serv
     * @param \Org\Swoole\客户端提交数据 $request
     */
    public function onOpen($serv, $request)
    {
//        file_put_contents(SWOOLE_TASK_PID_PATH, json_encode($serv));
//        if (!$this->_setting['daemonize']) {
//            echo 'Date:' . date('Y-m-d H:i:s') . "\t swoole_server master worker start\n";
//        }
//        $this->setProcessName($this->_setting['process_name'] . '-master');
//        //记录进程id,脚本实现自动重启
//        $pid = "{$serv->master_pid}\n{$serv->manager_pid}";
//        parent::onOpen($serv, $request); // TODO: Change the autogenerated stub
    }

    /**
     * 客户端发送数据服务端
     * @param \Org\Swoole\服务端信息 $serv
     * @param \Org\Swoole\客户端信息 $cli
     */
    public function onMessage($serv, $cli)
    {

    }

    /**
     * 客户端请求服务端
     * @param \Org\Swoole\客户端对服务器的请求数据 $request
     * @param $response
     */
    public function onRequest($request, $response)
    {
        foreach ($this->_serv->connections as $fd) {
            $this->serv->push($fd, $request->get['message']);
        } // TODO: Change the autogenerated stub
    }
}